# ML BootCamp Day2

In [9]:
import numpy as np

In [12]:
arr=np.array([1,2,3,4])

In [14]:
print(arr)

[1 2 3 4]


In [15]:
#types of array

In [16]:
arr3=np.ones((3,3))

In [17]:
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
arr4=np.zeros((3,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
arr5=np.arange(5)

In [21]:
arr5

array([0, 1, 2, 3, 4])

In [22]:
arr6=np.eye(4)

In [23]:
arr6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
arr7=np.linspace(0,16,num=5)
arr7

array([ 0.,  4.,  8., 12., 16.])

In [26]:
print(np.random.rand(4))

[0.72219653 0.79815005 0.45502568 0.98384484]


In [29]:
arr8=np.linspace(0,20,num=10)
arr8

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [30]:
for i in range(10):
    print(np.random.randint(5))

0
3
2
2
3
1
3
2
1
2


In [31]:
print(np.random.ranf(4))

[0.3415161  0.1734106  0.17573077 0.73411457]


In [32]:
print(np.random.randint(0,10,7))

[8 0 0 7 5 4 1]


In [34]:
print(np.random.randint(0,50,15))

[44 35 16  4 16 28 48 19 19 48 20 38 37 14  0]


In [35]:
arr9=np.random.randint(0,10,6)    #shortcut is shift+tab to get the information
arr9

array([2, 1, 0, 8, 9, 1])

In [36]:
arr9.shape

(6,)

In [38]:
arr9.reshape(2,3)

array([[2, 1, 0],
       [8, 9, 1]])

In [40]:
arr3=np.array([[1,2,3],[4,5,6],[6,7,8]])

In [41]:
arr3.shape

(3, 3)

In [42]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [43]:
arr3.reshape(-1)

array([1, 2, 3, 4, 5, 6, 6, 7, 8])

In [44]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [45]:
print(np.min(arr1))
print(np.max(arr1))
print(np.sqrt(arr1))
print(np.sin(arr1))
print(np.cos(arr1))

1
4
[1.         1.41421356 1.73205081 2.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [46]:
arr2=arr1
arr2[0]=5

In [47]:
print(arr2)
print(arr1)

[5 2 3 4]
[5 2 3 4]


In [48]:
T=(1,2,(3,4))  #my own attempt to make a nested tuple
print(T)

(1, 2, (3, 4))


In [49]:
arr1=np.array([1,2,3,4])

In [50]:
arr2=arr1.copy()
arr[2]=5

In [51]:
print(arr2)
print(arr1)

[1 2 3 4]
[1 2 3 4]


In [52]:
arr4=np.array(['hello','every','abcd','one'])

In [53]:
arr4

array(['hello', 'every', 'abcd', 'one'], dtype='<U5')

In [54]:
print(np.sort(arr4))

['abcd' 'every' 'hello' 'one']
